### ISSUE TITLE
Support OpenTelemetry

### ISSUE THREAD

**Issue by haines** [cerbos/cerbos-sdk-javascript#386]
## All client types

- [x] We should introduce a new package that instruments the clients by wrapping the transport, which means we'll get consistent spans for all client types. Done in #438.
- [x] Add [metrics](https://opentelemetry.io/docs/specs/otel/metrics/semantic_conventions/rpc-metrics/#rpc-client). Done in #644 

## gRPC

- [x] The [@opentelemetry/instrumentation-grpc](https://www.npmjs.com/package/@opentelemetry/instrumentation-grpc) doesn't work for us because we don't use a generated client class (we invoke RPCs directly through `Client#makeUnaryRequest`). Fixed in #438.
- [x] Propagate the span context via the request metadata using the W3C Trace Context format. Done in #638.

## HTTP

- [x] Propagate the span context via the request headers using the W3C Trace Context format. Done in #638.

**Comment by haines** [comment]
An initial release of [@cerbos/opentelemetry](https://www.npmjs.com/package/@cerbos/opentelemetry) (v0.1.0) is now available, which adds spans for Cerbos RPCs. It doesn't propagate the span context to the Cerbos server yet (that turned out to be non-trivial), but I'll look to add propagation in a future release.
